name = "wazweather"
compatibility_date = "2025-01-01"
main = "worker.js"

[assets]
directory = "wwwroot"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "waz_analytics"
database_name = "waz-analytics"
database_id = "38d497a4-5a97-41c4-b89c-1ba47a0dea4f"

[[d1_databases]]
binding = "IDENTITY_DB"
database_name = "dondlingergc-identity-db"
database_id = "1128e99a-70e1-458c-b0b7-d548a10a5533"

[triggers]
crons = ["* * * * *"]
