name = "blazorpwatemplate"
compatibility_date = "2024-05-26"

[build]
command = "bash build.sh"

[assets]
directory = "output/wwwroot"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[routes]]
pattern = "blazorpwa.dondlingergc.com"
custom_domain = true
