name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'
        
    - name: Publish Blazor Project
      run: dotnet publish -c Release -o release --nologo
      
    - name: Change base-tag in index.html
      run: sed -i 's/<base href="\/" \/>/<base href="\/BlazorPWATemplate\/" \/>/g' release/wwwroot/index.html
      
    - name: Fix SPA routing
      run: cp release/wwwroot/index.html release/wwwroot/404.html
      
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: release/wwwroot
